### PR TITLE
Update color legend and get color methods

### PR DESCRIPTION
**Pull request by comoglu**
to get better readability

### CODE REVIEW

**Comment by comoglu** [comment]
Screenshot_2024-08-21_17-51-40

**Comment by gempa-jabe** [comment]
I personally do not like the missing spacing in the legend cells and the different fonts (sans serif vs serif) in the table and the legend. The latter is not subject of this PR and just an addition.

**Comment by gempa-jabe** [comment]
I did not want to say that a white space should be inserted. Such things should be done with proper CSS which could be loaded from a file `style.css` which by default does not exist and users can just put it into the web folder and the browser will find and load it. @andres-h what do you think? This whole things needs an overhaul. I am personally unsure on how to proceed but of course we can merge this if it is acceptable by others as well.

**Comment by andres-h** [comment]
AFAICS the legend is now in sync with [BUD monitor](https://ds.iris.edu/bud_stuff/dmc/bud_monitor.ALL.html). Makes sense.

**Pull request merged**
