### PR TITLE
Tab2pid

### PR DESCRIPTION
**Pull request by pevans-gfz**
Extends tab2inv to support two new network attributes:

1. Na: Comment="This is commentary"
2. Na: Pid="doi:10.1234/xyz"

Both these result in <comment> objects in the resulting inventory.

      <comment>
        <text>This is commentary</text>
        <id>0</id>
      </comment>
 
      <comment>
        <text>doi:10.1234/xyz</text>
        <id>1</id>
      </comment>

The identifier number in `<id>` is arbitrary, based on order that `Na:` lines appear in the tab file.

There are a few new unit tests of the Tab class in the test directory.

**Note** After a pending SC schema update, there will be a place for the PIDs to be stored as identifiers in the db, and therefore exported to StationXML 1.1 as `<Identifier>`. But we are not there yet.

@andres-h does this look reasonable to you?

### CODE REVIEW

**Comment by andres-h** [comment]
Looks reasonable to me. Should we merge already?

**Comment by pevans-gfz** [comment]
> Looks reasonable to me. Should we merge already?

Yes, if you're happy with just the DOI text in `<text>`. If you'd prefer the JSONesque "{"type":"DOI","value":"10.15778/RESIF.FR"}", I'll do that.

**Comment by andres-h** [comment]
I'm confused. AFAICS it's [JSON already](https://github.com/SeisComP/extras/blob/e69b6b4b61243a44057e1bf947525b7e052ae608/nettab/libs/python/nettab/basesc3.py#L26). Just the DOI won't work.

**Comment by pevans-gfz** [comment]
> I'm confused. AFAICS it's [JSON already](https://github.com/SeisComP/extras/blob/e69b6b4b61243a44057e1bf947525b7e052ae608/nettab/libs/python/nettab/basesc3.py#L26). Just the DOI won't work.

Sorry, there was a bug hiding there. I set the text, not its JSONed version. Fixed with e183313

**Pull request merged**
